version: "3.2"

services:
    oragono:
        image: oragono/oragono:latest
        container_name: tripsit_irc_server
        restart: always
        ports:
            - "6667:6667/tcp"
            - "6697:6697/tcp"
        volumes:
            - tripsit_irc_server_data:/ircd

volumes:
    tripsit_irc_server_data:
